language: cpp
dist: trusty
sudo: required

matrix:
  include:
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        
before_install:
    - eval "${MATRIX_EVAL}"
    - ./install_ubuntu1604.sh
    - cd "${TRAVIS_BUILD_DIR}"
    
before_script:
  - PARENTDIR=$(pwd)
  - mkdir $PARENTDIR/build && cd $PARENTDIR/build
  

script:
  - cd $PARENTDIR/build
  - cmake -DCMAKE_BUILD_TYPE=Release $PARENTDIR
  - make

after_script:
  - cd $PARENTDIR/build/
  - ./graph_test
